services:
  workspace:
    build: .
    network_mode: host
    command: sleep infinity
    privileged: true
    volumes:
      - ../:/RarkHopper
      - ../.config/.gh:/home/vscode/.config/gh
      - /var/run/docker.sock:/var/run/docker.sock
  serena:
    image: ghcr.io/oraios/serena:latest
    stdin_open: true
